### ISSUE TITLE
Source map parsing error when used with create-react-app

### ISSUE THREAD

**Issue by hydrandt** [demvsystems/yup-ast#23]
In last version of react-scripts, warnings are now being shown for problems with parsing source maps in dependencies. As a result, with every run of react-scripts, there is a warning:

```
WARNING in ./node_modules/@demvsystems/yup-ast/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/hydrandt/ark/ark-react-frontend/frontend/node_modules/@demvsystems/yup-ast/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/hydrandt/ark/ark-react-frontend/frontend/node_modules/@demvsystems/yup-ast/src/index.ts'
```

There is a MR in react-scripts about disabling these warnings:

https://github.com/facebook/create-react-app/pull/11752

Still I thought it may be worth reporting.

**Comment by kassuro** [comment]
Thanks for submitting the issue. 
We will look into this after the holidays in January.

**Comment by kassuro** [comment]
Hey, so we checked this out and the warning is totally correct. Since we didn't include our sources in the package the source map referenced a file that does not exist in the package.

After some research we decided we include the source files in the package as you can see in #24 .

I have tested this locally already with CRA and didn't get any warnings for `yup-ast` :+1:
